### ISSUE TITLE
UFO/DS lib key `public.skipExportGlyphs` should be heeded

### ISSUE THREAD

**Issue by madig** [simoncozens/rust-font-tools#2]
See

* https://unifiedfontobject.org/versions/ufo3/lib.plist/#publicskipexportglyphs
* https://github.com/googlefonts/ufo2ft/blob/15f14d3c623728221feabd743cba41638483e5f8/Lib/ufo2ft/util.py#L42-L83
* Other places in ufo2ft where skipped glyphs are not passed on to feaLib

**Comment by madig** [comment]
Careful, this seems to just ignore non-exported glyphs. They have to be decomposed everywhere they're used (also matches Glyphs.app behavior).

**Comment by madig** [comment]
In fact, fonticulus now crashes on a project with:

> thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 18446744073709551614', C:\...\fonttools-rs\src\tables\hmtx.rs:34:16

**Comment by simoncozens** [comment]
Ack, I thought this was after decomposition. Will take a look.

**Comment by schriftgestalt** [comment]
You removed the check for `glyph.exported` but what about the `if subset.is_some() && !subset.as_ref().unwrap().contains(&glif.name.to_string())`. Shouldn’t that cause the same problems?

**Comment by madig** [comment]
Oops, it probably should :) Will make a new issue.
