### ISSUE TITLE
Cubic to quadratic conversion problem (off-curve node becomes on-curve)

### ISSUE THREAD

**Issue by justinpenner** [simoncozens/rust-font-tools#7]
The first node in each path is an off-curve point in the source, but Fonticulus is changing it to an on-curve point.

*Note: In Glyphs, each path has one node with an arrow on it. The arrow node is the **last** node (index -1) in the path, and it points toward the **first** node (index 0).*

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/46039243/170111465-2b32ef6a-d123-4aad-bf27-2612673cc844.png">

I also noticed that paths have a different starting node when building in Glyphs vs Fonticulus. Given a CCW exterior path, they will both reverse the node order to CW (TrueType requires CW), but Glyphs begins with node index -2 and ends at index -1, whereas Fonticulus begins with node index 0 and ends with index 1.

Here's my test file:
[slntAxisAltSubG3.zip](https://github.com/simoncozens/rust-font-tools/files/8766861/slntAxisAltSubG3.zip)

I hope that's helpful – let me know if you need any more info!

**Comment by simoncozens** [comment]
Thanks! This has some overlap with #3, although something *else* is not quite right about Glyphs files as well. I’ll take a look next week when back from holiday.
